version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net

  # jenkins:
  #   container_name: jenkins
  #   image: jenkins-docker
  #   restart: always
  #   build:
  #     context: pipeline
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - jenkins_home:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - net

  remote_host:
    container_name: remote-host
    image: remote-host
    restart: always
    build:
      context: centos
    networks:
      - net

  # db_host:
  #   container_name: db
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     - "MYSQL_ROOT_PASSWORD=1234"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - net

  # web:
  #   container_name: web
  #   image: ansible-web
  #   restart: always
  #   build:
  #     context: jenkins-ansible/web/
  #   ports:
  #     - "80:80"
  #   networks:
  #     - net

  # git:
  #   container_name: git-server
  #   image: 'gitlab/gitlab-ce:latest'
  #   restart: always
  #   hostname: 'gitlab.local'
  #   ports:
  #     - '8088:80'
  #   volumes:
  #     - '$GITLAB_HOME/gitlab/config:/etc/gitlab'
  #     - '$GITLAB_HOME/gitlab/logs:/var/log/gitlab'
  #     - '$GITLAB_HOME/gitlab/data:/var/opt/gitlab'
  #   networks:
  #     - net
    
volumes:
  jenkins_home:
  # db_data:

networks:
  net:
